### ISSUE TITLE
Can i use it with Laravel 4.2

### ISSUE THREAD

**Issue by Geekathon** [vinkla/vimeo#12]
Is this also compatible with laravel 4.2 ?

**Comment by GrahamCampbell** [comment]
Yes, use 1.x.

**Comment by GrahamCampbell** [comment]
Yes. Why did you even ask? Read the composer.json file... https://github.com/vinkla/vimeo/blob/1.1.0/composer.json#L17.

**Comment by Geekathon** [comment]
Oh my god! You are so awesome! I didn't even read that. I just read "Readme" and that says Laravel 5. 

Thank you so much .
