### ISSUE TITLE
Manager Class?

### ISSUE THREAD

**Issue by GrahamCampbell** [vinkla/vimeo#7]
Have you considered using my manager package to allow you to easily have multiple connections to vimeo?

**Comment by vinkla** [comment]
Don't know about it. How will it help? Do you have any example packages using it already?

**Comment by GrahamCampbell** [comment]
Yeh, I've got a few that use it and they've got pretty good unit tests. One sec...

**Comment by GrahamCampbell** [comment]
All work on Laravel 4.1/4.2/5.0.

Manager repo: https://github.com/GrahamCampbell/Laravel-Manager.

My packages that use it: https://github.com/GrahamCampbell/Laravel-Flysystem, https://github.com/GrahamCampbell/Laravel-Dropbox, https://github.com/GrahamCampbell/Laravel-DigitalOcean, https://github.com/GrahamCampbell/Laravel-GitHub.

Laravel-Dropbox is probably the simplest one to look at. The flysystem package is quite complex.

**Comment by vinkla** [comment]
Thanks! This looks quite nice. It provides a much easier coverage of testing facades etc. I'll look into it!

**Comment by vinkla** [comment]
@GrahamCampbell Off the topic, do you've any tips on working with packages locally. What is your workflow?

**Comment by GrahamCampbell** [comment]
I tend not to test that things work by putting them in apps, but by writing unit tests, and I'll often write a few basic functional tests when I done. I'd say my workflow for testing packages in applications is pretty shocking tbh - I'll literally just ftp over the changes.

**Comment by vinkla** [comment]
Sounds a bit dangerous but it also makes sense letting the tests speak for them selfs. Thanks for sharing!

**Comment by GrahamCampbell** [comment]
Once I've got a good test coverage, I can much more confidently refactor, and often won't check things work for myself. For example, I never actually tested the upgrade to flysystem 1.0 in my flysystem wrapper.

**Comment by vinkla** [comment]
Merged in d88951e.
