### ISSUE TITLE
Installation Process with Laravel 4

### ISSUE THREAD

**Issue by greeven** [vinkla/vimeo#8]
At this point "php artisan vendor:publish" I get "There are no commands defined in the "vendor" namespace.

So I copied the \vendor\vinkla\vimeo\src\config\config.php to \app\config\vimeo.php because that's what the command was supposed to do, right?

I inserted my identifier, code and token there but the basic example:
Vimeo::request('/me/videos', ['per_page' => 10], 'GET');

Just gives me:
array(3) { ["body"]=> NULL ["status"]=> int(0) ["headers"]=> array(0) { } }

Now I am lost.

Can you point me in the right direction? I don't know where to start to get a response from the api.
My goal ist to get infos about my videos which are not shown on vimeo and only embeddable on my site.

**Comment by vinkla** [comment]
The latest version doesn't support Laravel 4. Gry looking at the `1.0` branch instead https://github.com/vinkla/vimeo/blob/1.0/README.md

**Comment by greeven** [comment]
I did that.

The solution was that instead of "php artisan vendor:publish" one should use "php artisan config:publish vinkla/vimeo" instead.

And now that it works I also see my mistake in copying the config.php as vimeo.php directly into \config.

Thanks!

**Comment by vinkla** [comment]
The installation guide is different in the `1.0` branch. Great that you've got it up and running.
