### ISSUE TITLE
I have to upload video with privacy setting . How i can do this?

### ISSUE THREAD

**Issue by piyushpatil027** [vinkla/vimeo#9]
Hi @vinkla,

Hope you are doing great. I have used your library but I can not upload video with privacy setting. Is there any option to upload video with privacy setting. Please as soon reply me.

Thanks.

**Comment by vinkla** [comment]
Hi @piyushpatil027! This package utilizes the [vimeo/vimeo-api](https://github.com/vimeo/vimeo.php) package maybe better to [open up a issue](https://github.com/vimeo/vimeo.php/issues) at their repository instead since this is not Laravel specific.
